name: SIMMAC
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _r-mutex=1.0.0
  - attrs=19.3.0
  - backcall=0.1.0
  - bcrypt=3.1.7
  - binutils_impl_linux-64=2.33.1
  - binutils_linux-64=2.33.1
  - blas=1.0
  - bleach=3.1.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - cairo=1.14.12
  - certifi=2019.11.28
  - cffi=1.13.2
  - cryptography=2.8
  - curl=7.68.0
  - dbus=1.13.12
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gfortran_impl_linux-64=7.3.0
  - gfortran_linux-64=7.3.0
  - git=2.23.0
  - glib=2.63.1
  - gmp=6.1.2
  - graphite2=1.3.13
  - gsl=2.4
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - harfbuzz=1.8.8
  - icu=58.2
  - idna=2.8
  - importlib_metadata=1.5.0
  - inflect=4.1.0
  - intel-openmp=2020.0
  - ipykernel=5.1.4
  - ipyslurm=1.5.0
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jaraco.itertools=5.0.0
  - jedi=0.16.0
  - jinja2=2.11.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.1.0
  - jupyter_core=4.6.1
  - krb5=1.16.4
  - ld_impl_linux-64=2.33.1
  - libcurl=7.68.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc=7.2.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libssh2=1.8.2
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - make=4.2.1
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.2.0
  - mpi=1.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.1
  - notebook=6.0.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openmpi=4.0.2
  - openssl=1.1.1d
  - pandas=1.0.0
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - pango=1.42.4
  - paramiko=2.7.1
  - parso=0.6.0
  - pcre=8.43
  - perl=5.26.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - pixman=0.38.0
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.3
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.5.2
  - pynacl=1.3.0
  - pyqt=5.9.2
  - pyrsistent=0.15.7
  - python=3.8.1
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyzmq=18.1.1
  - qt=5.9.7
  - qtconsole=4.6.0
  - r-assertthat=0.2.1
  - r-backports=1.1.5
  - r-base=3.5.1
  - r-base64enc=0.1_3
  - r-cli=2.0.1
  - r-crayon=1.3.4
  - r-digest=0.6.23
  - r-ellipsis=0.3.0
  - r-evaluate=0.14
  - r-fansi=0.4.1
  - r-glue=1.3.1
  - r-htmltools=0.4.0
  - r-irdisplay=0.7
  - r-irkernel=1.1
  - r-jsonlite=1.6.1
  - r-pbdzmq=0.3_3
  - r-pillar=1.4.3
  - r-rcpp=1.0.3
  - r-repr=1.1.0
  - r-rlang=0.4.4
  - r-rmpi=0.6_9
  - r-utf8=1.1.4
  - r-uuid=0.1_2
  - r-vctrs=0.2.2
  - r-zeallot=0.1.0
  - readline=7.0
  - send2trash=1.5.0
  - setuptools=45.1.0
  - sip=4.19.13
  - six=1.14.0
  - sqlite=3.31.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tktable=2.10
  - tornado=6.0.3
  - traitlets=4.3.3
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=2.1.0
  - zlib=1.2.11
  - zstd=1.3.7


